<?php

namespace AppBundle\Repository;
use Doctrine\Common\Collections\Criteria;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostWithTags($idPost = null)
    {
        $qb = $this->createQueryBuilder('p');

        $qb
            ->join('p.tags', 'tags')
            ->orderBy('p.id', Criteria::DESC)
        ;

        if ($idPost) {
            $qb
                ->andWhere('p.id = :idPost')
                ->andWhere('p.postType = :news')
                ->setParameter('news', 'news')
                ->setParameter('idPost', $idPost);

            return $qb->getQuery()->getOneOrNullResult();
        }

        return $qb->getQuery()->getResult();
    }
}
