# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.type.post_ad:
        class: AppBundle\Form\PostAdType
        tags:
            - { name: app.form.type, alias: ad }
    app.form.type.post_news:
        class: AppBundle\Form\PostNewsType
        tags:
            - { name: app.form.type, alias: news }
    app.type_of_post:
        class: AppBundle\Form\TypesOfPost
        tags:
            - { name: app.type_of_post }